name: module3_task0
"on":
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Validate Makefile
      run: make help
      working-directory: module3_task0
